module.exports = {
	SITE_TITLE: "Silder",
	DEFAULT_PAGE: "pages/page",
	PORT: process.env.PORT || 1234,
	CONTENTFUL_ACCESS_TOKEN: process.env.CONTENTFUL_ACCESS_TOKEN,
	CONTENTFUL_SPACE: process.env.CONTENTFUL_SPACE,
	PRODUCT_CONTENTTYPE_ID: process.env.PRODUCT_CONTENTTYPE_ID
};